window.noir = {
  run: run,
  runCode: runCode,
  runSelection: runSelection,
  py: py,
  setCode: v => { const f = activeFile(); if (f && f.model) f.model.setValue(v); },
  setFont: setFont,
  downloadFile: downloadFile,
  toggleMinimap: toggleMinimap,
  toggleWrap: toggleWrap,
  share: buildShareLink,
  install: installPackage,
  copyOutput: copyOutput,
  importHash: importHash,
  repl: v => { replField.value = v; return replSubmit(); },
  view: v => setView(v, { force: true }),
  aiMode: (m) => { if (m){ S.prefs.ai.mode = m; savePrefs(); refreshAIChip(); } return S.prefs.ai; },
  aiModal: () => { openAIModal(); return !aiModal.hidden; },
  ghostItems: () => {
    const g = window.__noirGhost, model = editor && editor.getModel();
    if (!g || !model) return [];
    const pos = editor.getPosition();
    try { return g.compute(model, pos).map(i => i.insertText); } catch (e) { return ['ERR:' + (e && e.message)]; }
  },
  ghostShown: () => GHOST.shown ? GHOST.shown.insertText : null,
  ghostCalls: () => GHOST.calls,
  ghostAccept: () => { const g = window.__noirGhost; if (g) g.accept(); },
  ghostActions: () => editor ? editor.getSupportedActions().map(a => a.id).filter(id => /inline/i.test(id)) : [],
  profile: profileFile,
  lintFile: () => { const f = activeFile(); return f ? lintModel(f.model, true) : null; },
  markers: () => activeFile() ? monaco.editor.getModelMarkers({ owner: LINT_OWNER, resource: activeFile().model.uri }).map(m => m.message) : [],
  probChip: () => ({ hidden: stProb.hidden, e: spErr.textContent, w: spWarn.textContent }),
  snapCount: () => { const f = activeFile(); return f ? (SNAP[f.id] || []).length : 0; },
  openDiffFirst: () => { const f = activeFile(); const a = f && SNAP[f.id]; if (a && a.length){ openDiff(f, a[a.length - 1]); return true; } return false; },
  diffOpen: () => !diffWrap.hidden,
  closeDiff: closeDiff,
  restoreDiff: restoreDiff,
  searchFor: q => { setView('search', { force: true }); srQ.value = q; runSearch(); },
  searchState: () => ({ total: SR.total, files: SR.files, rows: srResults.querySelectorAll('.sr-m').length }),
  replaceAll: () => replaceIn(null),
  setReplace: v => { srR.value = v; },
  varsList: () => Array.from(vvList.querySelectorAll('.vv-row .vv-n')).map(e => e.textContent),
  ctxShow: ctxShow,
  plotCount: () => PLOTS.length,
  plots: () => PLOTS.map(p => ({ n: p.n, kb: Math.round(p.png.length * 3 / 4 / 1024) })),
  plotOpen: () => !plotWrap.hidden,
  openPlot: openPlot,
  closePlot: closePlot,
  viewPlots: () => setView('plots', { force: true }),
  format: formatDocument,
  tbLinks: () => Array.from(linesEl.querySelectorAll('.tb-link')).map(e => e.textContent),
  lastTrace: () => S.lastTrace,
  renameAt: renameSymbolAt,
  renameOpen: () => !!renameBox,
  closeRename: closeRenameBox,
  get pyReady(){ return S.pyReady; },
  get editor(){ return editor; }
};

